### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by huzhengkui** [Playwo/ChiaPool#5]
![image](https://user-images.githubusercontent.com/35648491/115245127-2e8ab100-a157-11eb-9d58-eb0559eb8a4c.png)
Hi, i got a  error.How can i  fix it?

**Comment by Playwo** [comment]
Are you using the latest dockerfile? There should only be 21 steps...

**Comment by Playwo** [comment]
It might also be your docker version. Can you run `docker --version` please

**Comment by huzhengkui** [comment]
Last login: Mon Apr 19 21:10:02 2021 from 117.152.156.63
root@kui:~# docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:

**Comment by huzhengkui** [comment]
Thanks for reply.

**Comment by huzhengkui** [comment]
root@kui:~/test_pool/ChiaPool/Docker/Server# vim docker-compose.yml 
root@kui:~/test_pool/ChiaPool/Docker/Server# docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
root@kui:~/test_pool/ChiaPool/Docker/Server# 
root@kui:~/test_pool/ChiaPool/Docker/Server# 
root@kui:~/test_pool/ChiaPool/Docker/Server# 
root@kui:~/test_pool/ChiaPool/Docker/Server# docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

**Comment by honyet** [comment]
---> Running in f05e8f9167d6
Cloning ChiaPool
Removing intermediate container f05e8f9167d6
 ---> f0889e07c054
Step 14/21 : RUN git clone https://github.com/Playwo/ChiaPool.git && cd ChiaPool/ChiaPool.Server && dotnet publish --runtime linux-x64 --self-contained -o /root/manager && chmod +x /root/manager/ChiaPool.Server
 ---> Running in c6b89d107fd2
Cloning into 'ChiaPool'...

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.202

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 16.9.0+57a23d249 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Failed to download package 'Microsoft.AspNetCore.SignalR.1.1.0' from 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.signalr/1.1.0/microsoft.aspnetcore.signalr.1.1.0.nupkg'.
  The download of 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.signalr/1.1.0/microsoft.aspnetcore.signalr.1.1.0.nupkg' timed out because no data was received for 60000ms.
    Exception of type 'System.TimeoutException' was thrown.

**Comment by Playwo** [comment]
@huzhengkui version 3.8 (which is used in the file) is definitely valid. It must be something on your end that is outdated, probably the docker-compose version. But you should be able to lower the version to something like 3.5, I'm pretty sure that it should still support the required features.

**Comment by Playwo** [comment]
@honyet Does this happen every time? Connection timeouts while restoring isn't something that I can tackle tho :/

**Comment by huzhengkui** [comment]
@Playwo  I dont know why the chiapoolserver alaways restarted. How to fix it? where is the server log?

![image](https://user-images.githubusercontent.com/35648491/115561639-565d4e80-a2e8-11eb-9ca3-5726f46f3345.png)

**Comment by honyet** [comment]
@Playwo yes,i think it's a problem with China's internet (:

**Comment by honyet** [comment]
hi, @Playwo ,now, Failed to run.

 ---> be0f168ecd54
Step 21/21 : ENTRYPOINT ["bash", "./entrypoint.sh"]
 ---> Running in ed983236b915
Removing intermediate container ed983236b915
 ---> a70a95651813
Successfully built a70a95651813
Successfully tagged chiapoolserver:latest
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# mv /root/ChiaPool/Docker/Server/entrypoint.sh .
mv: '/root/ChiaPool/Docker/Server/entrypoint.sh' and './entrypoint.sh' are the same file
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# vim pool.env
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# vim docker-compose.yml
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# vim docker-compose.yml

version: '3.8'
  
services:
  node:
    image: chiapoolserver
    ports:
      - 8444:8444
      - 8447:8447
      - 127.0.0.1:8666:8666
    restart: always
    container_name: ChiaNode
    volumes:
      - /logpath:/root/.chia/mainnet/log
      - /datapath/db:/root/.chia/mainnet/db
      - /datapath/wallet:/root.chia/mainnet/wallet
    cap_add:
      - NET_ADMIN
    env_file:
      - pool.env
      root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:28 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server#

**Comment by honyet** [comment]
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

**Comment by honyet** [comment]
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# vim docker-compose.yml

version: "2"   <===== here, '3.8' changed to "2",is right



root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# vim docker-compose.yml
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server# docker-compose up -d
Creating network "server_default" with the default driver
Creating ChiaNode ... done
root@iZj6cj2vifwdh0i96vsn5xZ:~/ChiaPool/Docker/Server#

**Comment by Playwo** [comment]
3.8 is a valid version as you can see in the compose file documenatation. But as long as everything works with 2 you're good to go

**Comment by Playwo** [comment]
> @Playwo yes,i think it's a problem with China's internet (:

Yep this makes sense

**Comment by huzhengkui** [comment]
@Playwo  Hi, how to fix this err?

![image](https://user-images.githubusercontent.com/35648491/115725092-1f546f00-a3b4-11eb-897e-b8b1f52ee22d.png)

**Comment by Playwo** [comment]
> @Playwo Hi, how to fix this err?
> 
> ![image](https://user-images.githubusercontent.com/35648491/115725092-1f546f00-a3b4-11eb-897e-b8b1f52ee22d.png)

Oh oops that is probably my mistake. Will fix later.

**Comment by Playwo** [comment]
> @Playwo by the way,what is the format of miner token? any example?

GUID, not the most secure but should be fine. You can get examples here: https://www.guidgenerator.com/

**Comment by huzhengkui** [comment]
@Playwo  Thanks a lot !

**Comment by huzhengkui** [comment]
@Playwo  Can I put the miner and server running on the same computer?

![image](https://user-images.githubusercontent.com/35648491/115993239-82d4db80-a604-11eb-920c-98f75d1a0d37.png)

**Comment by Playwo** [comment]
Yes you can. You probably just missed the ':' after the https

**Comment by huzhengkui** [comment]
@Playwo  how to fix this error?

![image](https://user-images.githubusercontent.com/35648491/115995171-bca9e000-a60c-11eb-8ad2-88e8d2973fa9.png)

**Comment by Playwo** [comment]
Is the server up an running? And does the connection work properly?

**Comment by huzhengkui** [comment]
@Playwo  server is running. 

![image](https://user-images.githubusercontent.com/35648491/115997657-883b2180-a616-11eb-9e53-a353da26fe74.png)

**Comment by huzhengkui** [comment]
@Playwo  By the way. Is there a website  from port 8666? I can't open it.

**Comment by Playwo** [comment]
> @Playwo server is running.
> 
> ![image](https://user-images.githubusercontent.com/35648491/115997657-883b2180-a616-11eb-9e53-a353da26fe74.png)

Hmm I guess it's something with the network setup. Docker networking is somewhat different from how you are used to do networking outside of docker. I cannot really help you with setting up the networking now. 
Will add example compose files for common uses like miner & pool on same machine later

**Comment by Playwo** [comment]
> @Playwo By the way. Is there a website from port 8666? I can't open it.

Website, No. Currently there are only API endpoints available which are used by the other nodes and the CLI. 
I have a overview website on my personal roadmap but for now It's more important to increase stability.
